image: registry.gitlab.com/codifryed/coolero/pipeline:v1

variables:
  POETRY_VIRTUALENVS_IN_PROJECT: "true"

cache:
  key: "${CI_JOB_NAME}"
  paths:
    - .cache/pip
    - .venv

before_script:
  - python --version
  - poetry --version
  - poetry install

stages:
  - quality
  - test
  - prepare_release
  - release

lint:
  stage: quality
  allow_failure: true
  script:
    - poetry run lint

test:
  stage: test
  script:
    - xvfb-run poetry run test

get_release_description:
  stage: prepare_release
  rules:
    - if: '$CI_COMMIT_TAG && $CI_COMMIT_BRANCH == "main"'
  script:
    - echo 'EXTRA_DESCRIPTION=$(awk \'s{ print ""; print}; $0~v {print; s=1; next}; s=0\' RS= v=${CI_COMMIT_TAG} ./CHANGELOG.md)' >> description.env
  artifacts:
    reports:
      dotenv: description.env

create_release:
  stage: release
  image: registry.gitlab.com/gitlab-org/release-cli:latest
  needs:
    - job: get_release_description
      artifacts: true
  rules:
    - if: '$CI_COMMIT_TAG && $CI_COMMIT_BRANCH == "main"'
  script:
    - echo 'running release job for v$CI_COMMIT_TAG'
  release:
    name: 'Coolero v$CI_COMMIT_TAG'
    description: '$EXTRA_DESCRIPTION'
    tag_name: '$CI_COMMIT_TAG'
    ref: '$CI_COMMIT_TAG'