image: registry.gitlab.com/codifryed/coolero/pipeline:v1

variables:
  POETRY_VIRTUALENVS_IN_PROJECT: "true"

cache:
  key: "${CI_JOB_NAME}"
  paths:
    - .cache/pip
    - .venv

before_script:
  - python --version
  - poetry --version
  - poetry install

stages:
  - quality
  - test
  - release

lint:
  stage: quality
  allow_failure: true
  script:
    - poetry run lint

test:
  stage: test
  script:
    - xvfb-run poetry run test