image: registry.gitlab.com/coolero/coolero/pipeline:v14

variables:
  POETRY_CACHE_DIR: "$CI_PROJECT_DIR/.pypoetry"
  CARGO_HOME: "$CI_PROJECT_DIR/.cargo"
  CCACHE_DIR: "$CI_PROJECT_DIR/.ccache"

stages:
  - test
  - compile
  - build_packages
  - test_packages
  - release

.cache_template: &cache_template
  cache:
    key: "${CI_JOB_NAME}"
    paths:
      # base path set in above envs
      - .pypoetry
      - .cargo
      - .ccache
      #- coolercontrold/target  # this can add up over time to a very large cache

.main_image_template: &main_image_template
  before_script:
    - python3.10 --version
    - poetry --version
    - rustup --version
    - cargo --version
    - rustc --version

# normal pipeline quick tests
############################################################################################

test_fast_metadata:
  stage: test
  rules:
    - if: $CI_PIPELINE_SOURCE == "push" && $CI_COMMIT_BRANCH != $CI_DEFAULT_BRANCH
  needs: [ ]
  script:
    - make validate-metadata

test_fast_liqctld:
  <<: *cache_template
  <<: *main_image_template
  stage: test
  rules:
    - if: $CI_PIPELINE_SOURCE == "push" && $CI_COMMIT_BRANCH != $CI_DEFAULT_BRANCH
  needs: [ ]
  script:
    - make test-fast-liqctld

test_fast_daemon:
  <<: *cache_template
  <<: *main_image_template
  stage: test
  rules:
    - if: $CI_PIPELINE_SOURCE == "push" && $CI_COMMIT_BRANCH != $CI_DEFAULT_BRANCH
  needs: [ ]
  script:
    - make test-fast-daemon
  artifacts:
    when: always
    reports:
      junit: coolercontrold/results.xml

test_fast_gui:
  <<: *cache_template
  <<: *main_image_template
  stage: test
  rules:
    - if: $CI_PIPELINE_SOURCE == "push" && $CI_COMMIT_BRANCH != $CI_DEFAULT_BRANCH
  needs: [ ]
  script:
    - make test-fast-gui


# compile all release artifacts
############################################################################################

compile_artifacts:
  # This is only a trigger to start the parallel jobs necessary
  stage: compile
  image: registry.gitlab.com/gitlab-org/release-cli:latest
  rules:
    - if: $CI_PIPELINE_SOURCE == "merge_request_event"
      when: on_success
    - if: $CI_PIPELINE_SOURCE == "push" && $CI_COMMIT_BRANCH == $CI_DEFAULT_BRANCH && ($CI_COMMIT_TAG == null || $CI_COMMIT_TAG == "")
      when: on_success
    - when: manual
      allow_failure: true
  needs: [ ]
  script:
    - echo "All release compilation jobs triggered."

compile_liqctld_bullseye:
  image: registry.gitlab.com/coolero/coolero/deb-bullseye:v14
  <<: *cache_template
  <<: *main_image_template
  stage: compile
  needs:
    - compile_artifacts
  script:
    - make test-liqctld
  artifacts:
    name: "CoolerControl-Liqctld_x64_${CI_COMMIT_SHORT_SHA}"
    paths:
      - coolercontrol-liqctld/coolercontrol-liqctld.dist
    expire_in: 7 days

compile_daemon_bullseye:
  image: registry.gitlab.com/coolero/coolero/deb-bullseye:v14
  <<: *cache_template
  <<: *main_image_template
  stage: compile
  needs:
    - compile_artifacts
  script:
    - make test-daemon
  artifacts:
    name: "CoolerControlD_x64_${CI_COMMIT_SHORT_SHA}"
    paths:
      - coolercontrold/coolercontrold
    expire_in: 7 days

compile_gui_bullseye:
  image: registry.gitlab.com/coolero/coolero/deb-bullseye:v14
  <<: *cache_template
  <<: *main_image_template
  stage: compile
  needs:
    - compile_artifacts
  script:
    - make test-gui
  artifacts:
    name: "CoolerControl_x64_${CI_COMMIT_SHORT_SHA}"
    paths:
      - coolercontrol-gui/coolercontrol.dist
    expire_in: 7 days

compile_liqctld_bookworm:
  image: registry.gitlab.com/coolero/coolero/deb-bookworm:v14
  <<: *cache_template
  <<: *main_image_template
  stage: compile
  needs:
    - compile_artifacts
  script:
    - make test-liqctld
  artifacts:
    name: "CoolerControl-Liqctld_x64_${CI_COMMIT_SHORT_SHA}"
    paths:
      - coolercontrol-liqctld/coolercontrol-liqctld.dist
    expire_in: 7 days

compile_daemon_bookworm:
  image: registry.gitlab.com/coolero/coolero/deb-bookworm:v14
  <<: *cache_template
  <<: *main_image_template
  stage: compile
  needs:
    - compile_artifacts
  script:
    - make test-daemon
  artifacts:
    name: "CoolerControlD_x64_${CI_COMMIT_SHORT_SHA}"
    paths:
      - coolercontrold/coolercontrold
    expire_in: 7 days

compile_gui_bookworm:
  image: registry.gitlab.com/coolero/coolero/deb-bookworm:v14
  <<: *cache_template
  <<: *main_image_template
  stage: compile
  needs:
    - compile_artifacts
  script:
    - make test-gui
  artifacts:
    name: "CoolerControl_x64_${CI_COMMIT_SHORT_SHA}"
    paths:
      - coolercontrol-gui/coolercontrol.dist
    expire_in: 7 days

compile_liqctld_fedora_35:
  image: registry.gitlab.com/coolero/coolero/fedora-35:v14
  <<: *cache_template
  <<: *main_image_template
  stage: compile
  needs:
    - compile_artifacts
  script:
    - make test-liqctld
  artifacts:
    name: "CoolerControl-Liqctld_x64_${CI_COMMIT_SHORT_SHA}"
    paths:
      - coolercontrol-liqctld/coolercontrol-liqctld.dist
    expire_in: 7 days

compile_daemon_fedora_35:
  image: registry.gitlab.com/coolero/coolero/fedora-35:v14
  <<: *cache_template
  <<: *main_image_template
  stage: compile
  needs:
    - compile_artifacts
  script:
    - make test-daemon
  artifacts:
    name: "CoolerControlD_x64_${CI_COMMIT_SHORT_SHA}"
    paths:
      - coolercontrold/coolercontrold
    expire_in: 7 days

compile_gui_fedora_35:
  image: registry.gitlab.com/coolero/coolero/fedora-35:v14
  <<: *cache_template
  <<: *main_image_template
  stage: compile
  needs:
    - compile_artifacts
  script:
    - make test-gui
  artifacts:
    name: "CoolerControl_x64_${CI_COMMIT_SHORT_SHA}"
    paths:
      - coolercontrol-gui/coolercontrol.dist
    expire_in: 7 days

# collect and package
############################################################################################

build_appimages:
  image: registry.gitlab.com/coolero/coolero/deb-bullseye:v14
  stage: build_packages
  dependencies:
    - compile_liqctld_bullseye
    - compile_daemon_bullseye
    - compile_gui_bullseye
  needs:
    - compile_liqctld_bullseye
    - compile_daemon_bullseye
    - compile_gui_bullseye
  script:
    - make appimage-daemon
    # bash can't find the appimage for whatever reason
    #- $CI_PROJECT_DIR/CoolerControlD-x86_64.AppImage --version
    - make appimage-gui
    #- $CI_PROJECT_DIR/CoolerControl-x86_64.AppImage --version
  artifacts:
    name: "CoolerControl_x86_64_${CI_COMMIT_SHORT_SHA}_AppImages"
    paths:
      - CoolerControlD-x86_64.AppImage
      - CoolerControl-x86_64.AppImage
    expire_in: 14 days

build_deb_bullseye:
  image: registry.gitlab.com/coolero/coolero/deb-bullseye:v14
  stage: build_packages
  dependencies:
    - compile_liqctld_bullseye
    - compile_daemon_bullseye
    - compile_gui_bullseye
  needs:
    - compile_liqctld_bullseye
    - compile_daemon_bullseye
    - compile_gui_bullseye
  script:
    - cd packaging
    - dpkg-architecture -l
    - dpkg-buildpackage -us -B
    - rm -f ../coolercontrol-dbgsym*.*deb
  artifacts:
    name: "CoolerControl_x86_64_deb_${CI_COMMIT_SHORT_SHA}"
    paths:
      - coolercontrol*.deb
    exclude:
      - coolercontrol-dbgsym*.*deb
    expire_in: 14 days

build_deb_bookworm:
  image: registry.gitlab.com/coolero/coolero/deb-bookworm:v14
  stage: build_packages
  dependencies:
    - compile_liqctld_bookworm
    - compile_daemon_bookworm
    - compile_gui_bookworm
  needs:
    - compile_liqctld_bookworm
    - compile_daemon_bookworm
    - compile_gui_bookworm
  script:
    - cd packaging
    - dpkg-architecture -l
    - dpkg-buildpackage -us -B
    - rm -f ../coolercontrol-dbgsym*.*deb
  artifacts:
    name: "CoolerControl_x86_64_deb_${CI_COMMIT_SHORT_SHA}"
    paths:
      - coolercontrol*.deb
    exclude:
      - coolercontrol-dbgsym*.*deb
    expire_in: 14 days

build_fedora_35:
  image: registry.gitlab.com/coolero/coolero/fedora-35:v14
  stage: build_packages
  dependencies:
    - compile_liqctld_fedora_35
    - compile_daemon_fedora_35
    - compile_gui_fedora_35
  needs:
    - compile_liqctld_fedora_35
    - compile_daemon_fedora_35
    - compile_gui_fedora_35
  script:
    - cp packaging/fedora/coolercontrol.spec /root/rpmbuild/SPECS/
    - mkdir /root/rpmbuild/SOURCES/CoolerControl
    - cp -r . /root/rpmbuild/SOURCES/CoolerControl/
    - cd /root/rpmbuild/SOURCES
    # todo: separate pristine source files from compiled ones
    - tar -cf CoolerControl.tar.gz CoolerControl/
    - cd ..
    # done in image to save bandwidth/speed:
    #- dnf builddep SPECS/coolercontrol.spec -y
    - rpmbuild -ba SPECS/coolercontrol.spec
    - cd RPMS/x86_64/
    - mv coolercontrol*.rpm ${CI_PROJECT_DIR}/
    - cd ${CI_PROJECT_DIR}
  artifacts:
    name: "CoolerControl_x86_64_rpm_${CI_COMMIT_SHORT_SHA}"
    paths:
      - coolercontrol*.rpm
    expire_in: 14 days

# test installation of packages
############################################################################################

test_deb_bullseye:
  stage: test_packages
  image: amd64/debian:bullseye
  dependencies:
    - build_deb_bullseye
  needs:
    - build_deb_bullseye
  script:
    - apt update
    - DEBIAN_FRONTEND=noninteractive apt install -yq --no-install-recommends ./coolercontrol*amd64.deb
    - coolercontrold --version
    - coolercontrol-liqctld --version
    - coolercontrol --version
    - apt remove -y coolercontrol

test_deb_bookworm:
  stage: test_packages
  image: amd64/debian:bookworm
  dependencies:
    - build_deb_bookworm
  needs:
    - build_deb_bookworm
  script:
    - apt update
    - DEBIAN_FRONTEND=noninteractive apt install -yq --no-install-recommends ./coolercontrol*amd64.deb
    - coolercontrold --version
    - coolercontrol-liqctld --version
    - coolercontrol --version
    - apt remove -y coolercontrol

test_deb_ubuntu_20.04:
  stage: test_packages
  image: ubuntu:focal
  dependencies:
    - build_deb_bullseye
  needs:
    - build_deb_bullseye
  script:
    - apt update
    - DEBIAN_FRONTEND=noninteractive apt install -yq --no-install-recommends ./coolercontrol*amd64.deb
    - coolercontrold --version
    - coolercontrol-liqctld --version
    - coolercontrol --version
    - apt remove -y coolercontrol

test_deb_ubuntu_22.04:
  stage: test_packages
  image: ubuntu:jammy
  dependencies:
    - build_deb_bookworm
  needs:
    - build_deb_bookworm
  script:
    - apt update
    - DEBIAN_FRONTEND=noninteractive apt install -yq --no-install-recommends ./coolercontrol*amd64.deb
    - coolercontrold --version
    - coolercontrol-liqctld --version
    - coolercontrol --version
    - apt remove -y coolercontrol

test_fedora_35:
  stage: test_packages
  image: fedora:35
  dependencies:
    - build_fedora_35
  needs:
    - build_fedora_35
  script:
    - yum -y localinstall ./coolercontrol*64.rpm
    - coolercontrold --version
    - coolercontrol-liqctld --version
    - coolercontrol --version
    - yum -y remove coolercontrol


# future CI features
############################################################################################

build_packages:
  stage: build_packages
  rules:
    - if: $CI_PIPELINE_SOURCE == "merge_request_event"
    - if: $CI_PIPELINE_SOURCE == "push" && $CI_COMMIT_BRANCH == $CI_DEFAULT_BRANCH && ($CI_COMMIT_TAG == null || $CI_COMMIT_TAG == "")
  script:
    - make build # -j3

create_release:
  stage: release
  image: registry.gitlab.com/gitlab-org/release-cli:latest
  before_script:
    - echo 'Starting release job'
  rules:
    - if: $CI_COMMIT_TAG && $CI_COMMIT_BRANCH == $CI_DEFAULT_BRANCH
  script:
    - echo "running release job for v${CI_COMMIT_TAG:?}"
    - awk -v ver="${CI_COMMIT_TAG:?}" '/^#+ \[/ { if (p) { exit }; if ($2 == "["ver"]") { p=1; next} } p && NF' ./CHANGELOG.md > ./description.txt
  release:
    name: 'CoolerControl v$CI_COMMIT_TAG'
    description: './description.txt'
    tag_name: '$CI_COMMIT_TAG'
    ref: '$CI_COMMIT_TAG'
    milestones:
      - '$CI_COMMIT_TAG'
    assets:
      links:
        - name: 'AppImage GUI'
          url: 'https://gitlab.com/api/v4/projects/30707566/packages/generic/appimage/$CI_COMMIT_TAG/CoolerControl-x86_64.AppImage'
          link_type: package
        - name: 'AppImage Daemon'
          url: 'https://gitlab.com/api/v4/projects/30707566/packages/generic/appimage/$CI_COMMIT_TAG/CoolerControlD-x86_64.AppImage'
          link_type: package
