[package]
name = "coolercontrol"
version = "1.4.1"
authors = ["Guy Boldon <gb@guyboldon.com>"]
edition = "2021"
# MSRV for all included libraries
rust-version = "1.81"
description = "Monitor and control your cooling and other devices"
documentation = "https://gitlab.com/coolercontrol/coolercontrol/-/wikis/home"
readme = false
homepage = "https://gitlab.com/coolercontrol/coolercontrol"
repository = "https://gitlab.com/coolercontrol/coolercontrol"
license = "GPL-3.0-or-later"

[build-dependencies]
tauri-build = { version = "=2.0.0-rc.12", features = [] }

[dependencies]
serde_json = "1.0.128"
serde = { version = "1.0.210", features = ["derive"] }
tauri = { version = "=2.0.0-rc.15", features = [
  "tray-icon",
  "image-ico",
  "image-png",
] }
# there is a schema-generated build issue with 2.0.0-rc.1 (vendor changes)
tauri-plugin-cli = { git = "https://github.com/tauri-apps/plugins-workspace.git", rev = "fb85e5dd76688f3ae836890160f9bde843b70167"}
tauri-plugin-clipboard-manager = "=2.0.0-rc.4"
tauri-plugin-shell = { git = "https://github.com/tauri-apps/plugins-workspace.git", rev = "fb85e5dd76688f3ae836890160f9bde843b70167"}
tauri-plugin-localhost = "=2.0.0-rc.1" # this allows the production build to access http://localhost
tauri-plugin-store = "=2.0.0-rc.3"
tauri-plugin-window-state = "=2.0.0-rc.5"
glib = "=0.18.5" # should follow the version Tauri uses
zbus = "=4.0.1" # should follow the version Tauri uses
rand = "0.8.5"

[features]
# this feature is used for production builds or when `devPath` points to the filesystem and the built-in dev server is disabled.
# If you use cargo directly instead of tauri's cli you can use this feature flag to switch between tauri's `dev` and `build` modes.
# DO NOT REMOVE!!
custom-protocol = ["tauri/custom-protocol"]

[profile.release]
strip = "symbols"
opt-level = 3
lto = "fat"
codegen-units = 1

[lints.clippy]
upper_case_acronyms = "allow"
type_complexity = "allow"
too_many_arguments = "allow"
doc_lazy_continuation = "allow"
