[package]
name = "coolercontrol"
version = "1.3.0"
authors = ["Guy Boldon <gb@guyboldon.com>"]
edition = "2021"
# MSRV for all included libraries
rust-version = "1.75"
description = "Monitor and control your cooling and other devices"
documentation = "https://gitlab.com/coolercontrol/coolercontrol/-/wikis/home"
readme = false
homepage = "https://gitlab.com/coolercontrol/coolercontrol"
repository = "https://gitlab.com/coolercontrol/coolercontrol"
license = "GPL-3.0-or-later"

[build-dependencies]
tauri-build = { version = "=2.0.0-beta.18", features = [] }

[dependencies]
serde_json = "1.0.120"
serde = { version = "1.0.204", features = ["derive"] }
tauri = { version = "=2.0.0-beta.23", features = [
  "tray-icon",
  "linux-ipc-protocol",
  "image-ico",
  "image-png",
] }
tauri-plugin-cli = "=2.0.0-beta.7"
tauri-plugin-clipboard-manager = "=2.1.0-beta.5"
tauri-plugin-shell = "=2.0.0-beta.8"
tauri-plugin-localhost = "=2.0.0-beta.7" # this allows the production build to access http://localhost
tauri-plugin-single-instance = "=2.0.0-beta.10"
tauri-plugin-store = "=2.0.0-beta.9"
tauri-plugin-window-state = "=2.0.0-beta.10"
rand = "0.8.5"

[features]
# this feature is used for production builds or when `devPath` points to the filesystem and the built-in dev server is disabled.
# If you use cargo directly instead of tauri's cli you can use this feature flag to switch between tauri's `dev` and `build` modes.
# DO NOT REMOVE!!
custom-protocol = ["tauri/custom-protocol"]

[profile.release]
strip = "symbols"
opt-level = 3
lto = "fat"
codegen-units = 1

[lints.clippy]
upper_case_acronyms = "allow"
type_complexity = "allow"
too_many_arguments = "allow"
