[package]
name = "coolercontrol"
version = "1.3.0"
authors = ["Guy Boldon <gb@guyboldon.com>"]
edition = "2021"
# MSRV for all included libraries
rust-version = "1.64"
description = "Monitor and control your cooling and other devices"
documentation = "https://gitlab.com/coolercontrol/coolercontrol/-/wikis/home"
readme = false
homepage = "https://gitlab.com/coolercontrol/coolercontrol"
repository = "https://gitlab.com/coolercontrol/coolercontrol"
license = "GPL-3.0-or-later"

[build-dependencies]
tauri-build = { version = "1.5.2", features = [] }

[dependencies]
serde_json = "1.0.117"
serde = { version = "1.0.202", features = ["derive"] }
tauri = { version = "1.6.7", features = [
  "cli",
  "window-set-focus",
  "window-unminimize",
  "window-show",
  "window-close",
  "window-hide",
  "shell-open",
  "process-relaunch",
  "clipboard-all",
  "system-tray",
] }
tauri-plugin-window-state = { git = "https://github.com/tauri-apps/plugins-workspace", rev = "5e3900e682e13f3759b439116ae2f77a6d389ca2" } # head of v1 branch
tauri-plugin-single-instance = { git = "https://github.com/tauri-apps/plugins-workspace", rev = "5e3900e682e13f3759b439116ae2f77a6d389ca2" }
tauri-plugin-localhost = { git = "https://github.com/tauri-apps/plugins-workspace", rev = "5e3900e682e13f3759b439116ae2f77a6d389ca2" } # this allows the production build to access http://localhost
tauri-plugin-store = { git = "https://github.com/tauri-apps/plugins-workspace", rev = "5e3900e682e13f3759b439116ae2f77a6d389ca2" }
rand = "0.8.5"

[features]
# this feature is used for production builds or when `devPath` points to the filesystem and the built-in dev server is disabled.
# If you use cargo directly instead of tauri's cli you can use this feature flag to switch between tauri's `dev` and `build` modes.
# DO NOT REMOVE!!
custom-protocol = ["tauri/custom-protocol"]

[profile.release]
lto = "fat"
codegen-units = 1

[lints.clippy]
upper_case_acronyms = "allow"
type_complexity = "allow"
too_many_arguments = "allow"
