[package]
name = "coolercontrol"
version = "1.0.4"
authors = ["Guy Boldon <gb@guyboldon.com>"]
edition = "2021"
rust-version = "1.60"
description = "Monitor and control your cooling and other devices"
documentation = "https://gitlab.com/coolercontrol/coolercontrol/-/wikis/home"
readme = false
homepage = "https://gitlab.com/coolercontrol/coolercontrol"
repository = "https://gitlab.com/coolercontrol/coolercontrol"
license = "GPL-3.0-or-later"

[build-dependencies]
tauri-build = { version = "1.5.1", features = [] }

[dependencies]
serde_json = "1.0.111"
serde = { version = "1.0.195", features = ["derive"] }
tauri = { version = "1.5.4", features = [
  "window-set-focus",
  "window-unminimize",
  "window-show",
  "window-close",
  "window-hide",
  "shell-open",
  "process-relaunch",
  "clipboard-all",
  "system-tray",
] }
tauri-plugin-window-state = { git = "https://github.com/tauri-apps/plugins-workspace", rev = "70d99086de3a58189d65c49954a3495972880725" } # head of v1 branch
tauri-plugin-single-instance = { git = "https://github.com/tauri-apps/plugins-workspace", rev = "70d99086de3a58189d65c49954a3495972880725" }
tauri-plugin-autostart = { git = "https://github.com/tauri-apps/plugins-workspace", rev = "70d99086de3a58189d65c49954a3495972880725" }
tauri-plugin-localhost = { git = "https://github.com/tauri-apps/plugins-workspace", rev = "70d99086de3a58189d65c49954a3495972880725" } # this allows the production build to access http://localhost
tauri-plugin-store = { git = "https://github.com/tauri-apps/plugins-workspace", rev = "70d99086de3a58189d65c49954a3495972880725" }
portpicker = "0.1.1"

[features]
# this feature is used for production builds or when `devPath` points to the filesystem and the built-in dev server is disabled.
# If you use cargo directly instead of tauri's cli you can use this feature flag to switch between tauri's `dev` and `build` modes.
# DO NOT REMOVE!!
custom-protocol = ["tauri/custom-protocol"]

[profile.release]
lto = "fat"
codegen-units = 1
