[package]
name = "coolercontrol"
version = "0.18.0"
#description = "A Tauri App"
#authors = ["codifryed"]
#license = ""
#repository = ""
#default-run = "app"
edition = "2021"
rust-version = "1.60"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[build-dependencies]
tauri-build = { version = "1.5.0", features = [] }

[dependencies]
serde_json = "1.0.107"
serde = { version = "1.0.190", features = ["derive"] }
tauri = { version = "1.5.2", features = [ "window-show", "window-close", "window-hide", "shell-open", "process-relaunch", "clipboard-all", "system-tray"] }
tauri-plugin-window-state = "0.1.0"
tauri-plugin-single-instance = { git = "https://github.com/tauri-apps/plugins-workspace", branch = "v1" }
tauri-plugin-autostart = { git = "https://github.com/tauri-apps/plugins-workspace", branch = "v1" }
tauri-plugin-localhost = "0.1.0" # this allows the production build to access http://localhost

[features]
# this feature is used for production builds or when `devPath` points to the filesystem and the built-in dev server is disabled.
# If you use cargo directly instead of tauri's cli you can use this feature flag to switch between tauri's `dev` and `build` modes.
# DO NOT REMOVE!!
custom-protocol = ["tauri/custom-protocol"]

[profile.release]
lto = "fat"
codegen-units = 1
