trailingComma: all
semi: false
singleQuote: true
printWidth: 100
proseWrap: preserve
tabWidth: 4
overrides:
  - files: ['*.yaml', '*.yml']
    options:
      tabWidth: 2
  - files: ['*.md']
    options:
      tabWidth: 2
      proseWrap: always
