FROM fedora:38

MAINTAINER codifryed

# Use C.UTF-8 locale to avoid issues with ASCII encoding
ENV LC_ALL C.UTF-8
ENV LANG C.UTF-8
ENV CI true
ENV PYTHONFAULTHANDLER=1 \
    PYTHONUNBUFFERED=1 \
    # pip
    PIP_NO_CACHE_DIR=off \
    PIP_DISABLE_PIP_VERSION_CHECK=on \
    PIP_DEFAULT_TIMEOUT=100

RUN dnf install -y \
    # basic packages
    file gcc make man sudo tar \
    # standard build deps
    curl wget openssl-devel bzip2-devel libffi-devel zlib-devel \
    dbus \
    # for standard appstream checks
    desktop-file-utils appstream \
    # tauri:
    webkit2gtk4.0-devel \
    libappindicator-gtk3-devel \
    librsvg2-devel \
    && \
    dnf groupinstall "C Development Tools and Libraries" -y && \
    # rpm building deps
    dnf install -y rpmdevtools dnf-plugins-core \
    systemd-rpm-macros libappstream-glib cargo-rpm-macros && \
    rpmdev-setuptree && \
    # build dependencies (to help speed up the build process) \
    dnf install -y python3-devel python3-wheel python3-liquidctl python3-setproctitle python3-fastapi python3-uvicorn \
    nodejs \
    npm && \
    # cleanup
    dnf clean all && \
  	rm -rf /var/cache/yum

# CI: for our conversion to gitlib junit test results
RUN cargo install cargo2junit
