[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"

[tool.poetry]
name = "coolercontrol-liqctld"
version = "0.14.0"
description = "Monitor and control your cooling and other devices"
authors = ["Guy Boldon <gb@guyboldon.com>"]
license = "GNU General Public License v3.0"
readme = "README.md"
repository = "https://gitlab.com/coolercontrol/coolercontrol"
homepage = "https://gitlab.com/coolercontrol/coolercontrol"
keywords = []
packages = [{ include = "coolercontrol-liqctld", from = "../"}]

[tool.poetry.urls]
issues = "https://gitlab.com/coolercontrol/coolercontrol/-/issues"

[tool.poetry.dependencies]
python = ">=3.9, <3.11"
liquidctl = "==1.11.1"
setproctitle = "==1.3.2"
fastapi = "==0.88.0"
uvicorn = "==0.20.0"
orjson = "==3.8.4"

[tool.poetry.dev-dependencies]
# Nuitka also has the following system dependencies when building:  gcc, ccache, chrpath, patchelf
nuitka = "==1.3.5"
pytest = "==7.2.0"

[tool.poetry.scripts]
liqctld = "coolercontrol-liqctld:main"
