[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"

[tool.poetry]
name = "coolercontrol_liqctld"
version = "0.15.0"
description = "Monitor and control your cooling and other devices"
authors = ["Guy Boldon <gb@guyboldon.com>"]
license = "GNU General Public License v3.0"
readme = "README.md"
repository = "https://gitlab.com/coolercontrol/coolercontrol"
homepage = "https://gitlab.com/coolercontrol/coolercontrol"
keywords = []
packages = [{ include = "coolercontrol_liqctld", from = ""}]

[tool.poetry.urls]
issues = "https://gitlab.com/coolercontrol/coolercontrol/-/issues"

[tool.poetry.dependencies]
python = ">=3.9, <3.12"
liquidctl = "==1.12.1"
setproctitle = "==1.3.2"
fastapi = "==0.95.1"
uvicorn = "==0.21.1"
orjson = "==3.8.10"

[tool.poetry.dev-dependencies]
# Nuitka also has the following system dependencies when building:  gcc, ccache, chrpath, patchelf
# Nuitka dependencies since 1.5.x don't play well with poetry and both projects don't seem willing to comprimise (old vs new pip standards)
#  so using git is required for everything to work correctly at the moment
nuitka = { git = "git@github.com:Nuitka/Nuitka.git", tag = "1.5.6" }
#pytest = "==7.2.1"

[tool.poetry.scripts]
coolercontrol-liqctld = "coolercontrol_liqctld.liqctld:main"
