[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"

[tool.poetry]
name = "coolercontrol_liqctld"
version = "0.16.0"
description = "Monitor and control your cooling and other devices"
authors = ["Guy Boldon <gb@guyboldon.com>"]
license = "GNU General Public License v3.0"
readme = "README.md"
repository = "https://gitlab.com/coolercontrol/coolercontrol"
homepage = "https://gitlab.com/coolercontrol/coolercontrol"
keywords = []
packages = [{ include = "coolercontrol_liqctld", from = ""}]

[tool.poetry.urls]
issues = "https://gitlab.com/coolercontrol/coolercontrol/-/issues"

[tool.poetry.dependencies]
python = ">=3.9, <3.12"
liquidctl = "==1.12.1"
setproctitle = "==1.3.2"
fastapi = "==0.95.1"
uvicorn = "==0.21.1"
orjson = "==3.8.10"

[tool.poetry.dev-dependencies]
# Nuitka also has the following system dependencies when building:  gcc, ccache, chrpath, patchelf
nuitka = "==1.5.6"
# there is currently a poetry issue getting the correct ordered-set package based on multiple requirements from Nuitka
# currenly the solution is to edit the .lock file by hand, removed the offending orderedset package, and adding the following explicitly:
ordered-set = "==4.1.0"
#pytest = "==7.2.1"

[tool.poetry.scripts]
coolercontrol-liqctld = "coolercontrol_liqctld.liqctld:main"
