# This is the CoolerControl configuration file.
# Comments and most formatting is preserved.

# Legacy690 Option for devices
# -------------------------------
# There are 2 Asetek 690LC liquid coolers that have the same device ID. 
#  To tell them apart we need user input to know which cooler we're actually dealing with.
#  This is an assignment of liquidctl AseTek690LC device UIDs to true/false:
#   true = Legacy690 Cooler aka NZXT Kraken X40, X60, X31, X41, X51 and X61
#   false = Modern690 Cooler aka EVGA CLC 120 (CLC12), 240, 280 and 360
# Example:
# 21091c4fb341ceab6236e8c9e905ccc263a4ac08134b036ed415925ba4c1645d = true
[legacy690]
21091c4fb341ceab6236e8c9e905ccc263a4ac08134b036ed415925ba4c1645d = true
