[package]
name = "coolercontrol"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
log = "0.4.17"
simple_logger = "2.2.0"
systemd-journal-logger = "0.5.0"
clap = { version = "3.2.16", features = ["derive"] }
anyhow = "1.0.58"
tokio = { version = "1.20.1", features = ["full"] }
tokio-cron-scheduler = "0.7.6"
tokio-graceful-shutdown = "0.10.1"
zmq = { version = "0.9.2", features = ["vendored"] }  # requires cmake to build libzmq locally
