[package]
name = "coolercontrol"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
log = "0.4.17"
simple_logger = "2.2.0"
systemd-journal-logger = "0.5.0"
clap = { version = "3.2.16", features = ["derive"] }  # Command line argument parser
anyhow = "1.0.58"  # easier error handling for our application
clokwerk = "0.3.5"  # schedule jobs
zmq = { version = "0.9.2", features = ["vendored"] }  # requires cmake to build libzmq locally
serde = { version = "1.0.140", features = ["derive"] }
serde_json = "1.0.82"
zbus = "3.0.0"  # our preferred DBus lib
sysinfo = { version = "0.25.0", default-features = false }  # gets detailed system info
chrono = { version = "0.4", features = ["serde"] }  # We use timestamps in our status history
strum = { version = "0.24", features = ["derive"] }  # Enum -> String
flume = "0.10.14"  # improved mpmc channels

[profile.release]
lto = "thin"
codegen-units = 1
