name: coolero
license: GPL-3.0+
icon: snap/gui/coolero-logo.png
grade: devel
confinement: classic
summary: Control your cooling
description: Coolero is a program to monitor and control your cooling devices.
base: core20
compression: lzo
adopt-info: coolero

parts:
  coolero:
    plugin: nil
    source: .
    override-pull: |
      snapcraftctl pull
      VERSION=$(awk -F'[ ="]+' '$1 == "version" { print $2 }' pyproject.toml)
      snapcraftctl set-version ${VERSION}
    build-packages:
      - ccache
      - python3.9
      - python3-pip
      - python3.9-dev
      - python3.9-venv
      - libusb-1.0-0
      - curl
      - git
      # for pyside
      - build-essential
      - libglu1-mesa-dev
      - libx11-xcb-dev
      - libxkbcommon-x11-0
    override-build: |
      # Install dependencies
      # wheel
      pip3 install --upgrade pip

      curl -sSL --output /tmp/install-poetry.py https://install.python-poetry.org
      python3.9 /tmp/install-poetry.py
      export PATH=$HOME/.local/bin:$PATH

      # Install all Poetry dependencies
      poetry config virtualenvs.create true
      poetry env use python3.9
      poetry install --no-root --no-dev

      make build
      cp -r dist/coolero/* ${SNAPCRAFT_PART_INSTALL}/
    stage-packages:
      # for OpenGL hardware access
      - libglu1-mesa
      - libopengl0
      # Qt desktop stuff
      - libxcb-randr0
      - libxcb-shape0
      - libusb-1.0-0
      - libgstreamer-gl1.0-0
      - libgstreamer1.0-0
      - libxkbfile1
      # Qt standard
      - libasound2
      - libatk1.0-0
      - libcairo2
      - libcairo-gobject2
      - libcups2
      - libdrm2
      - libegl1
      - libfreetype6
      - libgdk-pixbuf2.0-0
      - libgl1
      - libglvnd0
      - libglx0
      - libgtk-3-0
      - libharfbuzz0b
      - libicu66
      - libjpeg8
      - liblcms2-2
      - libnspr4
      - libnss3
      - libodbc1
      - libpango-1.0-0
      - libpangocairo-1.0-0
      - libpng16-16
      - libpq5
      - libpulse-mainloop-glib0
      - librsvg2-2
      - libspeechd2
      - libwayland-client0
      - libwayland-cursor0
      - libwayland-egl1
      - libwayland-server0
      - libx11-6
      - libx11-xcb1
      - libxau6
      - libxcb1
      - libxcb-glx0
      - libxcb-icccm4
      - libxcb-image0
      - libxcb-keysyms1
      - libxcb-render0
      - libxcb-render-util0
      - libxcb-shm0
      - libxcb-sync1
      - libxcb-xfixes0
      - libxcb-xinerama0
      - libxcb-xkb1
      - libxcomposite1
      - libxcursor1
      - libxdamage1
      - libxdmcp6
      - libxext6
      - libxfixes3
      - libxi6
      - libxkbcommon0
      - libxkbcommon-x11-0
      - libxml2
      - libxrandr2
      - libxrender1
      - libxslt1.1
      - libxtst6

apps:
  coolero:
    command: coolero
    plugs:
      - opengl
    environment:
      LANG: C.UTF-8
